[package]
name = "rusty-ziplod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
google-cloud-default = { version = "0.1.0", features = ["storage"] }
google-cloud-storage = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serenity = { version = "0.11.5", features = [
    "client",
    "standard_framework",
    "collector",
    "voice",
    "rustls_backend",
] }
songbird = { version = "0.2.2", features = ["gateway", "serenity", "rustls"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
